SELECT * FROM   T_ENTIER_ENT
WHERE  ENT_N NOT IN (SELECT ENTIER1.ENT_N FROM   T_ENTIER_ENT ENTIER1
                            CROSS JOIN T_ENTIER_ENT ENTIER2
                     WHERE  ENTIER1.ENT_N % ENTIER2.ENT_N = 0
                       AND  ENTIER2.ENT_N BETWEEN 2 AND ENTIER1.ENT_N -1)
ORDER BY 1 ;