Question 1:
SELECT CHB_NUM FROM   T_CHAMBRE_CHB WHERE  CHB_NUM NOT IN (SELECT CHB_NUM FROM   T_PLANNING_PLN WHERE  PLN_JOUR BETWEEN '2000-01-11' AND '2000-01-14' AND  PLN_LIBRE = 'False') ;

Question 2:
SELECT t_chambre_chb.CHB_NUM AS Numero_chambre, COALESCE(PLN_LIBRE, 'True') AS Planning_Libre FROM t_chambre_chb LEFT OUTER JOIN T_PLANNING_PLN ON t_chambre_chb.CHB_NUM = T_PLANNING_PLN.CHB_NUM WHERE PLN_JOUR = '2000-01-13' OR PLN_JOUR IS NULL ORDER BY t_chambre_chb.CHB_NUM;

Question 3:

